apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - kms:
       name: grpc-kms-provider
       endpoint: unix:///var/run/kmsplugin/grpc.sock
       cachesize: 1000
       timeout: 3s
    - identity: {}
